name: deploy
on:
  push:
    branches: [main]

jobs:
  check:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install zola
        run: sudo snap install --edge zola
      - name: Zola build
        run: zola --root zola-site build -o public
